export default {
  arrowParens: 'always',
  bracketSpacing: true,
  endOfLine: 'auto',
  jsxBracketSameLine: true,
  jsxSingleQuote: true,
  plugins: ['prettier-plugin-tailwindcss'],
  printWidth: 100,
  proseWrap: 'always',
  semi: true,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'all',
  useTabs: false,
}
